local comb = require("comb")

io.write("n: ")
local n = io.read()
io.write("k: ")
local k = io.read()
print("")

print("Factorial")
print(comb.factorial(n))
print("")
print("Permutation without repetition")
print(comb.A(n, k))
print("")
print("Permutation with repetition")
print(comb._A(n, k))
print("")
print("Combination without repetition")
print(comb.C(n, k))
print("")
print("Combination with repetition")
print(comb._C(n, k))
print("")
